### ISSUE TITLE
Vertical orientation does not work in Microsoft Edge

### ISSUE THREAD

**Issue by TaylorMutch** [consbio/Leaflet.Range#5]
Setting the `orient` parameter to `vertical` does not produce a vertical slider in Edge. See attached screenshots.

Normally the slider looks like this (Chrome 61):
![image](https://user-images.githubusercontent.com/10428066/32185606-e33007fa-bd5c-11e7-8144-9b43ae2a77b3.png)

In edge, there is a (very) small horizontal slider:
![image](https://user-images.githubusercontent.com/10428066/32185560-b4c5a0f0-bd5c-11e7-89a2-6bf3a2c7fa9f.png)
![image](https://user-images.githubusercontent.com/10428066/32185581-c87ebf96-bd5c-11e7-9778-a826e725ec97.png)

**Comment by nikmolnar** [comment]
Fixed in 0.1.4.
