### ISSUE TITLE
Change bar position

### ISSUE THREAD

**Issue by BulantsevOleg** [consbio/Leaflet.Range#6]
In the example slider position sets as "topright". Could you name another correct positions?

**Comment by nikmolnar** [comment]
Hi @BulantsevOleg ! This is like any other leaflet control, so any of the leaflet position will work: 'topleft', 'topright', 'bottomleft' or 'bottomright'.

http://leafletjs.com/reference-1.2.0.html#control-position

**Comment by BulantsevOleg** [comment]
Thanks, but I thought there is "middle" position:)

**Comment by nikmolnar** [comment]
Not that I see in the docs. But this control extends the base leaflet control, so anything that works for a regular leaflet control will also work for `Leaflet.Range`.
